import type { TableInfoData } from '@/lib/db/schemas'
import type { DatabaseTable } from '@/types'

export const DATABASE_TABLES = [
  'game',
  'list',
  'list_entry',
  'settings',
] as const

export const DATABASE_COLUMNS_BY_TABLE: Record<DatabaseTable, TableInfoData> = {
  game: [
    {
      cid: 0,
      name: 'id',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: null,
      pk: 1,
    },
    {
      cid: 1,
      name: 'name',
      type: 'TEXT',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 2,
      name: 'cover',
      type: 'TEXT',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 3,
      name: 'genres',
      type: 'TEXT',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 4,
      name: 'length',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 5,
      name: 'platform',
      type: 'TEXT',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 6,
      name: 'review_score',
      type: 'REAL',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 7,
      name: 'metadata1',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 8,
      name: 'metadata2',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 9,
      name: 'metadata3',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 10,
      name: 'metadata4',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 11,
      name: 'metadata5',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 12,
      name: 'created_at',
      type: 'TEXT',
      notnull: 0,
      dflt_value: 'CURRENT_TIMESTAMP',
      pk: 0,
    },
    {
      cid: 13,
      name: 'updated_at',
      type: 'TEXT',
      notnull: 0,
      dflt_value: 'CURRENT_TIMESTAMP',
      pk: 0,
    },
  ],
  list: [
    {
      cid: 0,
      name: 'id',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: null,
      pk: 1,
    },
    {
      cid: 1,
      name: 'name',
      type: 'TEXT',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 2,
      name: 'isMain',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '0',
      pk: 0,
    },
  ],
  list_entry: [
    {
      cid: 0,
      name: 'id',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: null,
      pk: 1,
    },
    {
      cid: 1,
      name: 'game_id',
      type: 'INTEGER',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 2,
      name: 'list_id',
      type: 'INTEGER',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 3,
      name: 'notes',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 4,
      name: 'position',
      type: 'INTEGER',
      notnull: 1,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 5,
      name: 'created_at',
      type: 'TEXT',
      notnull: 1,
      dflt_value: 'CURRENT_TIMESTAMP',
      pk: 0,
    },
    {
      cid: 6,
      name: 'updated_at',
      type: 'TEXT',
      notnull: 1,
      dflt_value: 'CURRENT_TIMESTAMP',
      pk: 0,
    },
  ],
  settings: [
    {
      cid: 0,
      name: 'id',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: null,
      pk: 1,
    },
    {
      cid: 1,
      name: 'displayed_metadata',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '0',
      pk: 0,
    },
    {
      cid: 2,
      name: 'metadata1_label',
      type: 'TEXT',
      notnull: 0,
      dflt_value: "'Expectation'",
      pk: 0,
    },
    {
      cid: 3,
      name: 'metadata1_presets',
      type: 'TEXT',
      notnull: 0,
      dflt_value:
        '\'["1 - Must Play", "2 - Highly Interested", "3 - Moderate Interest", "4 - Interested", "5 - Worth a Shot", "6 - Series Pending"]\'',
      pk: 0,
    },
    {
      cid: 4,
      name: 'metadata2_status',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '1',
      pk: 0,
    },
    {
      cid: 5,
      name: 'metadata2_label',
      type: 'TEXT',
      notnull: 0,
      dflt_value: "'Series'",
      pk: 0,
    },
    {
      cid: 6,
      name: 'metadata2_presets',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 7,
      name: 'metadata3_status',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '0',
      pk: 0,
    },
    {
      cid: 8,
      name: 'metadata3_label',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 9,
      name: 'metadata3_presets',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 10,
      name: 'metadata4_status',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '0',
      pk: 0,
    },
    {
      cid: 11,
      name: 'metadata4_label',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 12,
      name: 'metadata4_presets',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 13,
      name: 'metadata5_status',
      type: 'INTEGER',
      notnull: 0,
      dflt_value: '0',
      pk: 0,
    },
    {
      cid: 14,
      name: 'metadata5_label',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
    {
      cid: 15,
      name: 'metadata5_presets',
      type: 'TEXT',
      notnull: 0,
      dflt_value: null,
      pk: 0,
    },
  ],
}
